// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJx2GmlS80KdpkFXUWSZnlCU2kilS5-Oo',
    appId: '1:652394587641:web:63926df0e2334423548928',
    messagingSenderId: '652394587641',
    projectId: 'financemanager-87772',
    authDomain: 'financemanager-87772.firebaseapp.com',
    storageBucket: 'financemanager-87772.appspot.com',
    measurementId: 'G-N94VR30NPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN80XQ_4mAF9OEQ0WyvpSqBI2z3hXdWxg',
    appId: '1:652394587641:android:4b1e989ed768137d548928',
    messagingSenderId: '652394587641',
    projectId: 'financemanager-87772',
    storageBucket: 'financemanager-87772.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEK4CCndJdgIO7OJUhJ1eILa7wyHgxwOk',
    appId: '1:652394587641:ios:2554fe075b53981c548928',
    messagingSenderId: '652394587641',
    projectId: 'financemanager-87772',
    storageBucket: 'financemanager-87772.appspot.com',
    iosBundleId: 'com.example.financeManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEK4CCndJdgIO7OJUhJ1eILa7wyHgxwOk',
    appId: '1:652394587641:ios:e5eb0634aefef40b548928',
    messagingSenderId: '652394587641',
    projectId: 'financemanager-87772',
    storageBucket: 'financemanager-87772.appspot.com',
    iosBundleId: 'com.example.financeManager.RunnerTests',
  );
}
